#!/usr/bin/env bash

# setup the virtual environment, if not already setup

if [ ! -d "venv" ]; then
  echo "setting up virtual environment";
  virtualenv -p python3 venv;
  echo "installing requirements"
  source venv/bin/activate;
  pip install -r requirements.txt;
fi

# activate the venv

echo "activating virtual environment";
source venv/bin/activate;


